apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.appname }}
    tag: {{ .Values.image.tag }}
  name:  "{{ .Values.appname }}-{{ .Values.image.tag }}"
  namespace: {{ .Values.namespace.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.appname }}
      tag: {{ .Values.image.tag }}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ .Values.appname }}
        tag: {{ .Values.image.tag }}
    spec:
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
            - containerPort: {{ .Values.containerPort }}
        imagePullPolicy: {{ .Values.image.imagePullPolicy }}
        name: "{{ .Values.appname }}-{{ .Values.image.tag }}"
        resources:
          requests:
            cpu: {{ .Values.resources.requests.CPU }}
            memory: {{ .Values.resources.requests.memory }}
          limits:
            cpu: {{ .Values.resources.limits.CPU }}
            memory: {{ .Values.resources.limits.memory }}
        livenessProbe:
            httpGet:
              path: {{ .Values.livenessProbe }}
              port: {{ .Values.containerPort }}
        readinessProbe:
            httpGet:
              path: {{ .Values.readinessProbe }}
              port: {{ .Values.containerPort }}

            
