apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: techtrends-prod
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      ## define the input values file
      valueFiles:
      - values-prod.yaml
    path: helm/ 
    repoURL: https://github.com/Abdullah-Ashehry/techtrends-k8
    targetRevision: HEAD
  # Sync policy
  syncPolicy: {}
