namespace:
  name: staging

service:
  port: 5111

replicaCount: 3

resources:
  requests:
    CPU: "90m"         # CPU request in millicores (90m = 0.09 cores)
    memory: "300Mi"    # Memory request in MiB
  limits:
    CPU: "128m"        # CPU limit in millicores (128m = 0.128 cores)
    memory: "500Mi"    # Memory limit in MiB