namespace:
  name: prod

service:
  port: 7111

replicaCount: 5

image:
  imagePullPolicy: Always

resources:
  requests:
    CPU: "128m"       
    memory: "350Mi" 
  limits:
    CPU: "256m"
    memory: "500Mi"
